# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: ekidd/rust-musl-builder:latest

# Defines stages which are to be executed
stages:
  - build

# Run `cargo build` for the project with stable Rust
run-build:
  stage: build
  image: rust:latest
  script:
  - rustup target add x86_64-unknown-linux-musl
  - rustc --version && cargo --version
  - cargo build --release --target x86_64-unknown-linux-musl --jobs 1
  - cp target/release/non-answer-generator ./non-answer-generator
  - cp example/config.json ./config.json
  artifacts:
    paths:
      - non-answer-generator
      - config.json
      - README.md
