# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: ekidd/rust-musl-builder:latest

# Defines stages which are to be executed
stages:
  - build

# build-linux:
#   stage: build
#   image: ekidd/rust-musl-builder:latest
#   script:
#   - rustc --version && cargo --version
#   - cargo build --release --jobs 1
#   - cp target/release/non-answer-generator ./non-answer-generator
#   - cp example/config.json ./config.json
#   artifacts:
#     paths:
#       - non-answer-generator
#       - config.json
#       - README.md
#   cache:
#     paths:
#       - target/
#       - .cargo/
#   variables:
#     GIT_STRATEGY: fetch
#     CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

build-windows:
  image: omnijar/rust:windows
  stage: build
  script:
    - cargo build --release --target x86_64-pc-windows-msvc
  artifacts:
    paths:
      - target
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - target/
  variables:
    GIT_STRATEGY: fetch
